galaxy_info:
  author: Geert Geurts <geert@verweggistan.eu>
  description: Partition and install a server from the initramfs build with dracut-tuxifier
  issue_tracker_url: https://github.com/Geertsky/ansible-install_initramfs/issues
  license: EUPL 1.2


  platforms:
    - name: Fedora
      versions:
        - 38
    - name: Rocky
      versions:
        - 8
        - 9
        - 10
    - name: Almalinux
      versions:
        - 9
        - 10

  galaxy_tags:
    - minimal_install
    - operating_system
    - OS

  dependencies:
    - community.general
    - ansible.posix
