---

- name: "De-activate any volume groups"
  ansible.builtin.shell: |
    for VG in $(lvm vgs --noheadings -o vg_name); do
      lvm lvchange --activate n $VG;
    done
  register: clean_installdisk__vgscript
  changed_when: clean_installdisk__vgscript.rc != 0

- name: "Zero MBR"
  ansible.builtin.shell: |
    wipefs -af "{{ item.device }}"
  loop: "{{ installdisk.disks }}"
  register: clean_installdisk__dd
  failed_when: clean_installdisk__dd.rc != 0

- name: "Reload partitions"
  ansible.builtin.shell: |
    blockdev --rereadpt {{ item.device }}
  loop: "{{ installdisk.disks }}"
  register: clean_installdisk__blockdev
  failed_when: clean_installdisk__blockdev.rc != 0
