---

- name: Copy rpm gpg key for distribution
  ansible.builtin.copy:
    src: "{{ gpg_key }}"
    dest: "/tmp/"
    mode: "0644"
    owner: root
    group: root

- name: Import gpg key
  ansible.builtin.command:
    argv:
      - rpmkeys
      - --dbpath=/tuxifier-sysroot/var/lib/rpm
      - --define
      - "_var /tuxifier-sysroot/var"
      - --define
      - "_tmppath /var/tmp"
      - --define
      - "__urlhelpercmd /local/conda/envs/tuxifier-python/bin/curl"
      - --define
      - "__urlhelper_localopts --retry=10 --retry-all-errors --cacert=/etc/pki/tls/certs/ca-bundle.crt"
      - --import
      - "/tmp/{{ gpg_key | basename }}"

- name: Resolve install urls
  geertsky.tuxifier.generate_minimal_install_urls_info:
    distribution: "{{ distribution }}"
  register: generate_minimal_install
  delegate_to: localhost
  vars:
    ansible_shell_executable: /bin/sh

- name: Install the rpms
  ansible.builtin.command:
    argv: "{{ rpm_argv + generate_minimal_install.urls }}"
  register: rpm_output

- name: "Resolve relocated rpmdb"
  when: '(rpmdb_reimport is defined and rpmdb_reimport) or False'
  ansible.builtin.command:
    argv:
      - chroot
      - /tuxifier-sysroot
      - /bin/sh
      - -c
      - 'rpmdb --exportdb >/tmp/rpmdb&&mv /var/lib/rpm/rpmdb* /tmp/&&cat /tmp/rpmdb|rpmdb --importdb'
  register: rpmdb_import
  failed_when: '(rpmdb_reimport is defined and rpmdb_reimport) and rpmdb_import.rc != 0'
