---

rpmdb_reimport: false
distribution:
  name: 'fedora'
  arch: 'x86_64'
  version: '38'
  repo:
    type: 'metalink'
    url: 'https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch'
  minimalpackages:
    - '@Core'
    - 'util-linux'
    - "{{ 'kernel-' ~ ansible_facts['kernel'] if (continue_install | default(false) | bool) else 'kernel' }}"
    - 'grub2-efi-x64'
    - 'grub2-tools-efi'
    - 'grub2-pc'
    - 'lvm2'
    - 'shim-x64'
    - 'efibootmgr'
    - 'python3'
    - 'selinux-policy-targeted'
