ansible_interpreter_python_fallback:
  - /local/conda/envs/bambini-python/bin/python3
  - /local/conda/envs/bambini-python/bin/python
  - python3.14
  - python3.13
  - python3.12
  - python3.11
  - python3.10
  - python3.9
  - /usr/bin/python3
  - python3
