---
rpmdb_reimport: false
distribution:
  name: 'rocky'
  arch: 'x86_64'
  version: '10'
  repo:
    type: 'baseurl'
    url: 'https://mirror.puzzle.ch/rockylinux/10/BaseOS/x86_64/os/'
  minimalpackages:
    - '@Core'
    - 'util-linux'
    - 'kernel'
    - 'grub2-efi-x64'
    - 'grub2-tools-efi'
    - 'grub2-pc'
    - 'efibootmgr'
    - 'lvm2'
    - 'shim-x64'
    - 'python3'
    - 'selinux-policy-targeted'
