---
rpmdb_reimport: True
distribution:
  name: 'rocky'
  arch: 'x86_64'
  version: '8'
  repo:
    type: 'baseurl'
    url: 'https://mirror.puzzle.ch/rockylinux/8/BaseOS/x86_64/os/'
  minimalpackages:
    - '@Core'
    - 'util-linux'
    - 'kernel'
    - 'grub2-efi-x64'
    - 'grub2-tools-efi'
    - 'grub2-pc'
    - 'shim-x64'
    - 'lvm2'
    - 'efibootmgr'
    - 'platform-python'
    - 'sqlite'

gpg_key: etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-8
