---
- name: Resolve install urls
  geertsky.bambini.generate_minimal_install_urls_info:
    distribution: "{{ distribution }}"
  register: generate_minimal_install
  delegate_to: localhost

- name: Install the rpms
  ansible.builtin.shell: |
     set -o pipefail
     rpm --dbpath=/var/lib/rpm \
     --root=/sysroot \
     --define '_var /var' \
     --define '_tmppath /var/tmp' \
     --define '__urlhelpercmd /local/conda/envs/bambini-python/bin/curl' \
     --verbose \
     --install {{ generate_minimal_install.rpm_urls }}
  register: rpm_output
  #    {{ rpm_additional_macros | join(' ') }} \

- name: "Resolve relocated rpmdb" # https://fedoraproject.org/wiki/Changes/RelocateRPMToUsr
  ansible.builtin.shell:
    cmd: 'set -o pipefail && rpmdb --root=/sysroot --exportdb|chroot /sysroot rpmdb --importdb'
  when: '(rpmdb_reimport is defined and rpmdb_reimport) or False'
  register: rpmdb_relocate
  failed_when: '(rpmdb_reimport is defined and rpmdb_reimport) and rpmdb_relocate.rc != 0'
